# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'showList' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]

  # Pods for showList

  target 'showListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'showListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
